language: objective-c
osx_image: xcode8.3
script:
 - travis_retry fastlane ios test
# - fastlane android test
 - sleep 20
before_install:
 - brew update; brew update # Workaround for https://github.com/Homebrew/homebrew/issues/42553
 - brew outdated xctool || brew upgrade xctool
# - gem install fastlane
